- name: Create directory for SSL
  file:
    path: /etc/ssl/ansible
    state: directory
    mode: '0755'

- name: Generate private key (4096, RSA)
  openssl_privatekey:
    path: /etc/ssl/ansible/tower.oldstable.me.uk.key

#- name: Create SSL CSR Request
#  openssl_csr:
#    path: /etc/ssl/ansible/tower.oldstable.me.uk.csr
#    privatekey_path: /etc/ssl/ansible/tower.oldstable.me.uk.key
#    common_name: oldstable.me.uk
#  delegate_to: smallstep.oldstable.me.uk
#  become: yes

- meta: clear_facts

- name: Sign Certificate Request
  expect:
    command: step ca certificate tower.oldstable.me.uk /home/ec2-user/tower.crt /home/ec2-user/tower.key
    responses:
      Please enter the password to decrypt the provisioner key: "password"
  delegate_to: smallstep.oldstable.me.uk
  become: yes

#- name: Sign Certificate Request
#  command: step certificate sign /etc/ssl/ansible/tower.oldstable.me.uk.csr /root/.step/certs/root_ca.crt /root/.step/secrets/root_ca_key
#  delegate_to: smallstep.oldstable.me.uk
#  become: yes

- meta: clear_facts

- name: Move Cert to desired host.
  command: rsync -avzhe "ssh -i /home/ec2-user/.ssh/my.key" /home/ /home/ec2-user/tower.* ec2-user@tower.oldstable.me.uk:/home/ec2-user/
  delegate_to: smallstep.oldstable.me.uk

- meta: clear_facts
